/**
 * The Steward Spirit - Room Population & Maintenance
 *
 * When GodAI creates a location, The Steward receives the room specification and:
 * 1. Generates appropriate entities (objects, items, furniture, resources)
 * 2. Ensures descriptions match actual entity contents
 * 3. Maintains room coherence over time
 * 4. Requests systems/components from The Weaver when needed
 *
 * The key principle: If a room description says "flour sacks line the walls",
 * there MUST be flour_sack entities. Agents should never perceive things that
 * don't exist in the ECS.
 */

import { google } from "@ai-sdk/google";
import { generateText } from "ai";
import type { SpiritRegistry } from "./spirit-registry";
import { createSpirit } from "./spirit-registry";
import type { SpiritDefinition, SpiritState, DivineMessage } from "./types";
import { worldSchema, type ObjectTypeDefinition, type StimulusDefinition, type StateDefinition } from "../world/schema";
import { ObjectManager } from "../world/object-manager";

// =============================================================================
// TYPES
// =============================================================================

/**
 * A room creation request delegated from GodAI
 */
export interface RoomCreationRequest {
  id: string;
  timestamp: number;
  requestedBy: number; // Spirit EID (usually God)
  roomType: string; // e.g., "bakery", "blacksmith", "tavern"
  roomName: string;
  context: {
    worldTheme?: string; // e.g., "medieval fantasy", "cyberpunk"
    economyLevel?: "poor" | "modest" | "prosperous" | "wealthy";
    primaryFunction?: string; // What the room is for
    inhabitants?: string[]; // Who will use this room
    connectedRooms?: string[]; // Nearby rooms for context
  };
  constraints?: {
    maxItems?: number;
    requiredItems?: string[]; // Must include these
    forbiddenItems?: string[]; // Must NOT include these
    budgetLevel?: "sparse" | "normal" | "abundant";
  };
}

/**
 * Stimulus emission definition for an entity
 */
export interface StimulusEmission {
  type: "visual" | "smell" | "sound" | "heat" | "cold" | "tactile";
  template: string; // What agents perceive, e.g., "The forge glows with hot coals"
  interval?: number; // Emission interval in ms (default: 5000)
  intensity?: number; // 0-1, affects perception priority (default: 0.5)
}

/**
 * An entity specification generated by The Steward
 */
export interface RoomEntitySpec {
  name: string;
  type: "object" | "furniture" | "container" | "resource" | "tool" | "decoration" | "station";
  description: string; // Internal description (for WorldSchema)
  material?: string;
  quantity?: number; // For resources/consumables
  portable: boolean;
  interactable: boolean;
  affordances?: string[]; // What can be done with this
  components?: string[]; // ECS components to add

  // Stimulus-based perception (dynamic, not static)
  stimuli: StimulusEmission[]; // What this entity emits for agents to perceive
}

/**
 * A fully populated room specification
 */
export interface PopulatedRoom {
  requestId: string;
  roomName: string;
  roomType: string;

  // Entities to create (each with their own stimuli)
  entities: RoomEntitySpec[];

  // Ambient stimulus sources (room-level stimuli not tied to specific objects)
  ambientStimuli: StimulusEmission[];

  // Legacy support (optional) - can be used for debugging
  generatedDescription?: string;

  // Legacy ambience (converted to ambientStimuli internally)
  ambience?: {
    sounds?: string[];
    smells?: string[];
    lighting?: string;
    temperature?: string;
  };

  // What systems/components might be needed
  systemRequests?: SystemRequest[];

  // Metadata
  timestamp: number;
  status: "pending" | "created" | "failed";
}

/**
 * A request for The Weaver to create new systems/components
 */
export interface SystemRequest {
  type: "system" | "component";
  name: string;
  reason: string;
  specification?: string;
}

// =============================================================================
// ROOM TYPE TEMPLATES
// =============================================================================

/**
 * Templates for common room types - used as guidance for generation
 */
const ROOM_TEMPLATES: Record<string, {
  coreItems: string[];
  optionalItems: string[];
  stations: string[];
  ambience: { sounds: string[]; smells: string[] };
}> = {
  bakery: {
    coreItems: ["flour_sack", "yeast_jar", "salt_box", "water_bucket", "bread_basket"],
    optionalItems: ["sugar_sack", "honey_pot", "butter_crock", "egg_basket", "spice_rack"],
    stations: ["stone_oven", "kneading_table", "proofing_shelf", "cooling_rack"],
    ambience: {
      sounds: ["fire crackling", "dough being kneaded"],
      smells: ["fresh bread", "yeast", "wood smoke"],
    },
  },
  blacksmith: {
    coreItems: ["iron_ingot", "coal_pile", "hammer", "tongs", "water_trough"],
    optionalItems: ["steel_ingot", "copper_ingot", "horseshoes", "nails_box", "oil_can"],
    stations: ["forge", "anvil", "bellows", "grinding_stone", "quench_barrel"],
    ambience: {
      sounds: ["hammer on metal", "fire roaring", "bellows pumping"],
      smells: ["hot metal", "coal smoke", "oil"],
    },
  },
  tavern: {
    coreItems: ["ale_barrel", "wine_bottles", "mugs", "plates", "bread_loaf"],
    optionalItems: ["cheese_wheel", "dried_meat", "pickled_vegetables", "dice_set", "coin_purse"],
    stations: ["bar_counter", "kitchen_hearth", "serving_table"],
    ambience: {
      sounds: ["murmured conversations", "clinking glasses", "fire crackling"],
      smells: ["ale", "roasting meat", "wood smoke"],
    },
  },
  herbalist: {
    coreItems: ["mortar_pestle", "herb_bundles", "glass_vials", "dried_flowers", "medicinal_roots"],
    optionalItems: ["healing_salve", "fever_remedy", "sleeping_draught", "bandages", "honey_pot"],
    stations: ["drying_rack", "preparation_table", "storage_cabinet", "garden_window"],
    ambience: {
      sounds: ["herbs being ground", "bubbling pot"],
      smells: ["lavender", "mint", "chamomile", "earthy herbs"],
    },
  },
  general_store: {
    coreItems: ["rope_coil", "lantern", "candles", "cloth_bolts", "tools_assortment"],
    optionalItems: ["pots_pans", "nails_box", "seeds_packets", "soap_bars", "thread_spools"],
    stations: ["sales_counter", "display_shelves", "storage_room_door"],
    ambience: {
      sounds: ["coins counting", "door bell"],
      smells: ["wood", "canvas", "soap"],
    },
  },
  library: {
    coreItems: ["book_stack", "ink_pot", "quills", "parchment_sheets", "candle_holder"],
    optionalItems: ["ancient_tome", "scroll_case", "magnifying_glass", "wax_seal", "sand_shaker"],
    stations: ["reading_desk", "book_shelves", "scribe_table"],
    ambience: {
      sounds: ["pages turning", "quill scratching", "quiet whispers"],
      smells: ["old paper", "ink", "candle wax"],
    },
  },
  bedroom: {
    coreItems: ["bed", "pillow", "blanket", "chamber_pot", "candle_holder"],
    optionalItems: ["wardrobe", "mirror", "wash_basin", "rug", "personal_chest"],
    stations: ["bedside_table", "writing_desk"],
    ambience: {
      sounds: ["creaking floorboards"],
      smells: ["clean linens", "wood"],
    },
  },
};

// =============================================================================
// STATE
// =============================================================================

interface StewardState {
  pendingRequests: RoomCreationRequest[];
  completedRooms: PopulatedRoom[];
  systemRequests: SystemRequest[];
  roomInventory: Map<string, string[]>; // roomName -> entity names
}

let stewardState: StewardState = {
  pendingRequests: [],
  completedRooms: [],
  systemRequests: [],
  roomInventory: new Map(),
};

export function getStewardState(): StewardState {
  return stewardState;
}

export function resetStewardState(): void {
  stewardState = {
    pendingRequests: [],
    completedRooms: [],
    systemRequests: [],
    roomInventory: new Map(),
  };
}

// =============================================================================
// ROOM CREATION REQUEST HANDLING
// =============================================================================

let requestIdCounter = 0;

/**
 * Submit a room creation request to The Steward
 */
export function requestRoomPopulation(
  roomType: string,
  roomName: string,
  context: RoomCreationRequest["context"] = {},
  constraints: RoomCreationRequest["constraints"] = {},
  requestedBy: number = 0
): RoomCreationRequest {
  const request: RoomCreationRequest = {
    id: `room_${++requestIdCounter}_${Date.now()}`,
    timestamp: Date.now(),
    requestedBy,
    roomType,
    roomName,
    context,
    constraints,
  };

  stewardState.pendingRequests.push(request);
  console.log(`[Steward] Room population request received: ${roomName} (${roomType})`);

  return request;
}

/**
 * Get pending room requests
 */
export function getPendingRoomRequests(): RoomCreationRequest[] {
  return stewardState.pendingRequests;
}

// =============================================================================
// AI-POWERED ROOM POPULATION
// =============================================================================

/**
 * Generate a populated room specification using AI
 */
export async function generateRoomPopulation(
  request: RoomCreationRequest
): Promise<PopulatedRoom | null> {
  const model = google("gemini-2.0-flash");

  // Get template hints if available
  const template = ROOM_TEMPLATES[request.roomType.toLowerCase().replace(/\s+/g, "_")];

  const templateHint = template
    ? `
TEMPLATE HINTS for ${request.roomType}:
- Core items typically found: ${template.coreItems.join(", ")}
- Optional items: ${template.optionalItems.join(", ")}
- Work stations: ${template.stations.join(", ")}
- Typical sounds: ${template.ambience.sounds.join(", ")}
- Typical smells: ${template.ambience.smells.join(", ")}
`
    : "";

  const prompt = `You are The Steward, a spirit responsible for furnishing and populating rooms in a living simulation.

TASK: Generate a complete entity manifest for "${request.roomName}" (a ${request.roomType}).

CONTEXT:
- World theme: ${request.context.worldTheme || "medieval fantasy"}
- Economy level: ${request.context.economyLevel || "modest"}
- Primary function: ${request.context.primaryFunction || `A working ${request.roomType}`}
- Inhabitants: ${request.context.inhabitants?.join(", ") || "Various villagers"}
${templateHint}

CONSTRAINTS:
- Max items: ${request.constraints?.maxItems || 15}
- Budget: ${request.constraints?.budgetLevel || "normal"}
${request.constraints?.requiredItems?.length ? `- MUST include: ${request.constraints.requiredItems.join(", ")}` : ""}
${request.constraints?.forbiddenItems?.length ? `- MUST NOT include: ${request.constraints.forbiddenItems.join(", ")}` : ""}

RULES:
1. Generate 8-15 entities that would realistically be in this room
2. Each entity must be concrete and tangible - no abstract concepts
3. Include a mix of: furniture, tools, resources/consumables, containers, decorations
4. Resources should have quantities (e.g., "flour_sack" with quantity 50)
5. Mark items as portable (can be picked up) or not
6. Consider what agents would actually need to DO their job here

CRITICAL - STIMULUS-BASED PERCEPTION:
Instead of static descriptions, each entity EMITS STIMULI that agents perceive.
- A lit forge emits: visual ("Glowing coals illuminate the forge"), heat ("Waves of heat radiate from the forge"), sound ("The fire crackles and roars")
- Fresh bread emits: visual ("Golden loaves cool on the rack"), smell ("The aroma of fresh-baked bread fills the air")
- An anvil might emit: visual ("A heavy iron anvil sits ready"), sound (only when in use - leave empty if idle)

Agents perceive rooms DYNAMICALLY through what's emitting. No static room descriptions!

Respond with a JSON object in this exact format:
{
  "entities": [
    {
      "name": "entity_name_snake_case",
      "type": "object|furniture|container|resource|tool|decoration|station",
      "description": "Brief internal description for WorldSchema",
      "material": "wood|iron|stone|cloth|glass|leather|etc",
      "quantity": null or number for consumables,
      "portable": true/false,
      "interactable": true/false,
      "affordances": ["action1", "action2"],
      "stimuli": [
        {
          "type": "visual|smell|sound|heat|cold|tactile",
          "template": "What agents perceive, written as sensory description",
          "intensity": 0.1 to 1.0 (how noticeable)
        }
      ]
    }
  ],
  "ambientStimuli": [
    {
      "type": "sound|smell|visual",
      "template": "Room-level ambient stimuli not tied to specific objects, e.g., 'Dust motes drift in the light'",
      "intensity": 0.3
    }
  ],
  "systemRequests": [
    {
      "type": "system|component",
      "name": "name of system/component needed",
      "reason": "why this is needed for the room to function"
    }
  ] or empty array if none needed
}`;

  try {
    const response = await generateText({
      model,
      prompt,
      temperature: 0.7,
    });

    // Parse JSON from response
    const jsonMatch = response.text.match(/\{[\s\S]*\}/);
    if (!jsonMatch) {
      console.error("[Steward] Failed to extract JSON from response");
      return null;
    }

    const parsed = JSON.parse(jsonMatch[0]);

    // Parse stimuli with defaults
    const parseStimuli = (stimuliArray: any[]): StimulusEmission[] => {
      if (!stimuliArray || !Array.isArray(stimuliArray)) return [];
      return stimuliArray.map((s: any) => ({
        type: s.type || "visual",
        template: s.template || "",
        interval: s.interval ?? 5000,
        intensity: s.intensity ?? 0.5,
      }));
    };

    const populatedRoom: PopulatedRoom = {
      requestId: request.id,
      roomName: request.roomName,
      roomType: request.roomType,
      entities: parsed.entities.map((e: any) => ({
        name: e.name,
        type: e.type,
        description: e.description,
        material: e.material,
        quantity: e.quantity,
        portable: e.portable ?? false,
        interactable: e.interactable ?? true,
        affordances: e.affordances || [],
        stimuli: parseStimuli(e.stimuli),
        components: inferComponents(e),
      })),
      ambientStimuli: parseStimuli(parsed.ambientStimuli),
      // Legacy support - convert old ambience to stimuli if present
      ambience: parsed.ambience,
      generatedDescription: parsed.generatedDescription, // Optional, for debugging
      systemRequests: parsed.systemRequests || [],
      timestamp: Date.now(),
      status: "pending",
    };

    // Track entities for this room
    stewardState.roomInventory.set(
      request.roomName,
      populatedRoom.entities.map(e => e.name)
    );

    // Remove from pending, add to completed
    stewardState.pendingRequests = stewardState.pendingRequests.filter(
      r => r.id !== request.id
    );
    stewardState.completedRooms.push(populatedRoom);

    // Track system requests
    if (populatedRoom.systemRequests && populatedRoom.systemRequests.length > 0) {
      stewardState.systemRequests.push(...populatedRoom.systemRequests);
    }

    console.log(`[Steward] Generated ${populatedRoom.entities.length} entities for ${request.roomName}`);

    return populatedRoom;
  } catch (error) {
    console.error("[Steward] Error generating room population:", error);
    return null;
  }
}

/**
 * Infer which ECS components an entity should have based on its type
 */
function inferComponents(entity: any): string[] {
  const components: string[] = ["Name", "Description"];

  switch (entity.type) {
    case "resource":
      components.push("Consumable");
      if (entity.quantity) components.push("Quantity");
      break;
    case "container":
      components.push("Container", "Inventory");
      break;
    case "tool":
      components.push("Tool", "Usable");
      break;
    case "station":
      components.push("Station", "Interactable");
      break;
    case "furniture":
      components.push("Furniture");
      break;
    case "decoration":
      components.push("Decoration");
      break;
  }

  if (entity.portable) {
    components.push("Portable");
  }

  if (entity.interactable) {
    components.push("Interactable");
  }

  // Add StimulusSource if entity has stimuli
  if (entity.stimuli && entity.stimuli.length > 0) {
    components.push("StimulusSource");
  }

  return components;
}

// =============================================================================
// ROOM MAINTENANCE
// =============================================================================

/**
 * Check if a room needs replenishment
 */
export function checkRoomNeeds(roomName: string, currentEntities: string[]): {
  missing: string[];
  depleted: string[];
  recommendations: string[];
} {
  const originalEntities = stewardState.roomInventory.get(roomName) || [];
  const missing = originalEntities.filter(e => !currentEntities.includes(e));

  // Find depleted resources (would need quantity tracking from ECS)
  const depleted: string[] = [];

  // Generate recommendations
  const recommendations: string[] = [];
  if (missing.length > 0) {
    recommendations.push(`Replenish missing items: ${missing.join(", ")}`);
  }

  return { missing, depleted, recommendations };
}

/**
 * Generate replenishment spec for a room
 */
export async function generateReplenishment(
  roomName: string,
  missingItems: string[],
  context: string
): Promise<RoomEntitySpec[]> {
  const model = google("gemini-2.0-flash");

  const prompt = `You are The Steward. A room needs replenishment.

ROOM: ${roomName}
MISSING ITEMS: ${missingItems.join(", ")}
CONTEXT: ${context}

Generate specifications for replacing these items. Keep them consistent with the room's theme.

Respond with a JSON array:
[
  {
    "name": "item_name",
    "type": "resource|tool|etc",
    "description": "brief description",
    "material": "material type",
    "quantity": number or null,
    "portable": true/false,
    "interactable": true/false
  }
]`;

  try {
    const response = await generateText({
      model,
      prompt,
      temperature: 0.5,
    });

    const jsonMatch = response.text.match(/\[[\s\S]*\]/);
    if (!jsonMatch) return [];

    return JSON.parse(jsonMatch[0]);
  } catch (error) {
    console.error("[Steward] Error generating replenishment:", error);
    return [];
  }
}

// =============================================================================
// UPWARD COMMUNICATION (TO WEAVER)
// =============================================================================

/**
 * Send system requests to The Weaver
 */
export function sendSystemRequestsToWeaver(registry: SpiritRegistry): number {
  const pendingRequests = stewardState.systemRequests.filter(
    r => !r.specification // Not yet sent
  );

  if (pendingRequests.length === 0) return 0;

  // Find The Steward and The Weaver spirits
  const steward = registry.byName.get("The Steward");
  const weaver = registry.byName.get("The Weaver");

  if (!steward || !weaver) {
    console.warn("[Steward] Cannot send requests - spirits not found");
    return 0;
  }

  // Get the actual spirit states
  const stewardSpirit = registry.spirits.get(steward);
  const weaverSpirit = registry.spirits.get(weaver);

  if (!stewardSpirit || !weaverSpirit) {
    console.warn("[Steward] Cannot send requests - spirit states not found");
    return 0;
  }

  for (const request of pendingRequests) {
    const message: DivineMessage = {
      id: `steward_req_${Date.now()}_${Math.random().toString(36).slice(2, 7)}`,
      timestamp: Date.now(),
      from: steward,
      to: weaver,
      type: "request",
      domain: "locale",
      priority: "normal",
      subject: `${request.type === "system" ? "System" : "Component"} Request: ${request.name}`,
      content: `The Steward requests a new ${request.type} to support room functionality.\n\nName: ${request.name}\nReason: ${request.reason}`,
      requiresResponse: true,
    };

    // Push directly to The Weaver's inbox
    weaverSpirit.inbox.push(message);

    // Mark as sent
    request.specification = "sent";
  }

  console.log(`[Steward] Sent ${pendingRequests.length} system requests to The Weaver`);
  return pendingRequests.length;
}

// =============================================================================
// WORLDSCHEMA-INTEGRATED POPULATION (PREFERRED)
// =============================================================================

/**
 * Populated room result using WorldSchema
 */
export interface SchemaPopulatedRoom {
  roomName: string;
  roomType: string;
  /** Entity IDs created via ObjectManager */
  entityIds: number[];
  /** Types registered with WorldSchema */
  registeredTypes: string[];
  /** Ambient stimulus sources created */
  ambientEntityIds: number[];
}

/**
 * Generate and spawn room entities using WorldSchema + ObjectManager
 * This is the PREFERRED approach - entities are defined in WorldSchema
 * and created via ObjectManager.spawn() which handles all ECS wiring.
 */
export async function populateRoomViaSchema(
  world: any,
  request: RoomCreationRequest,
  roomEid: number // EID of the room entity to populate
): Promise<SchemaPopulatedRoom | null> {
  const model = google("gemini-2.0-flash");
  const objectManager = new ObjectManager(world);

  // Get template hints if available
  const template = ROOM_TEMPLATES[request.roomType.toLowerCase().replace(/\s+/g, "_")];

  // First, check what types already exist in WorldSchema
  const existingTypes = worldSchema.getAllObjectTypes().map(t => t.name);

  const prompt = `You are The Steward, populating a room using the WorldSchema system.

TASK: Define what entities should exist in "${request.roomName}" (a ${request.roomType}).

CONTEXT:
- World theme: ${request.context.worldTheme || "medieval fantasy"}
- Economy level: ${request.context.economyLevel || "modest"}
- Primary function: ${request.context.primaryFunction || `A working ${request.roomType}`}

EXISTING OBJECT TYPES IN SCHEMA:
${existingTypes.join(", ")}

${template ? `
TEMPLATE HINTS for ${request.roomType}:
- Core items: ${template.coreItems.join(", ")}
- Stations: ${template.stations.join(", ")}
` : ""}

RULES:
1. For each entity, either USE an existing type OR DEFINE a new one
2. Each new type definition must include:
   - name (snake_case)
   - description (can use {variable} placeholders)
   - traits (what can be done with it)
   - states with stimuli (what agents perceive in each state)
   - category
3. Stimuli are how agents PERCEIVE - each state should emit sensory data (visual, smell, sound, heat, etc.)
4. Generate 8-15 entities total

Respond with JSON:
{
  "newTypes": [
    {
      "name": "flour_sack",
      "description": "A burlap sack of {quality} flour",
      "traits": ["takeable", "examinable", "consumable"],
      "category": "resource",
      "variables": { "quality": { "type": "string", "default": "fine" } },
      "defaultState": "full",
      "states": {
        "full": {
          "description": "A full sack of flour.",
          "stimuli": [
            { "type": "visual", "template": "A bulging sack of flour leans against the wall", "intensity": 0.5 },
            { "type": "smell", "template": "The faint dusty smell of flour", "intensity": 0.3 }
          ]
        },
        "empty": {
          "description": "An empty flour sack.",
          "stimuli": [
            { "type": "visual", "template": "A deflated, empty flour sack lies crumpled", "intensity": 0.3 }
          ]
        }
      }
    }
  ],
  "entities": [
    { "type": "flour_sack", "properties": { "quality": "fine" }, "state": "full" },
    { "type": "torch", "state": "lit" }
  ],
  "ambientStimuli": [
    { "type": "sound", "template": "The creak of wooden floorboards", "intensity": 0.2 }
  ]
}`;

  try {
    const response = await generateText({
      model,
      prompt,
      temperature: 0.7,
    });

    const jsonMatch = response.text.match(/\{[\s\S]*\}/);
    if (!jsonMatch) {
      console.error("[Steward] Failed to extract JSON from schema response");
      return null;
    }

    const parsed = JSON.parse(jsonMatch[0]);
    const result: SchemaPopulatedRoom = {
      roomName: request.roomName,
      roomType: request.roomType,
      entityIds: [],
      registeredTypes: [],
      ambientEntityIds: [],
    };

    // Register new types with WorldSchema
    if (parsed.newTypes && Array.isArray(parsed.newTypes)) {
      for (const typeDef of parsed.newTypes) {
        // Convert to proper ObjectTypeDefinition format
        const fullDef: ObjectTypeDefinition = {
          name: typeDef.name,
          description: typeDef.description,
          traits: typeDef.traits || [],
          states: typeDef.states || { normal: { description: "A " + typeDef.name } },
          defaultState: typeDef.defaultState || "normal",
          category: typeDef.category,
          variables: typeDef.variables,
          transitions: typeDef.transitions,
          defaultComponents: typeDef.defaultComponents,
        };

        // Only register if not already in schema
        if (!worldSchema.getObjectType(typeDef.name)) {
          worldSchema.defineObjectType(fullDef);
          result.registeredTypes.push(typeDef.name);
          console.log(`[Steward] Registered new type: ${typeDef.name}`);
        }
      }
    }

    // Spawn entities via ObjectManager
    if (parsed.entities && Array.isArray(parsed.entities)) {
      for (const entitySpec of parsed.entities) {
        const typeId = entitySpec.type;
        const typeDef = worldSchema.getObjectType(typeId);

        if (!typeDef) {
          console.warn(`[Steward] Unknown type: ${typeId}, skipping`);
          continue;
        }

        const eid = objectManager.spawn(typeId, {
          containedIn: roomEid,
          state: entitySpec.state,
          properties: entitySpec.properties,
        });

        if (eid !== null) {
          result.entityIds.push(eid);
        }
      }
    }

    // Create ambient stimulus sources (room-level stimuli)
    if (parsed.ambientStimuli && Array.isArray(parsed.ambientStimuli)) {
      for (const ambientStim of parsed.ambientStimuli) {
        // Create a simple stimulus source entity for ambient effects
        const eid = objectManager.spawnCustom({
          name: `ambient_${ambientStim.type}_${Date.now()}`,
          description: ambientStim.template,
          traits: ["ambient", "stimulus_source"],
          containedIn: roomEid,
        });
        result.ambientEntityIds.push(eid);
      }
    }

    console.log(`[Steward] Schema-populated ${request.roomName}: ${result.entityIds.length} entities, ${result.registeredTypes.length} new types`);

    // Track in steward state
    stewardState.roomInventory.set(request.roomName, result.entityIds.map(e => `eid_${e}`));

    // Remove from pending
    stewardState.pendingRequests = stewardState.pendingRequests.filter(r => r.id !== request.id);

    return result;
  } catch (error) {
    console.error("[Steward] Error in schema population:", error);
    return null;
  }
}

// =============================================================================
// MAIN CYCLE
// =============================================================================

/**
 * Run The Steward's main cycle
 */
export async function runStewardCycle(
  registry: SpiritRegistry
): Promise<{
  roomsPopulated: number;
  entitiesGenerated: number;
  systemRequestsSent: number;
}> {
  let roomsPopulated = 0;
  let entitiesGenerated = 0;

  // Process pending room requests
  for (const request of [...stewardState.pendingRequests]) {
    const populatedRoom = await generateRoomPopulation(request);
    if (populatedRoom) {
      roomsPopulated++;
      entitiesGenerated += populatedRoom.entities.length;
    }
  }

  // Send any accumulated system requests
  const systemRequestsSent = sendSystemRequestsToWeaver(registry);

  return {
    roomsPopulated,
    entitiesGenerated,
    systemRequestsSent,
  };
}

// =============================================================================
// SPIRIT DEFINITION
// =============================================================================

const StewardDefinition: SpiritDefinition = {
  name: "The Steward",
  domain: "locale",
  rank: "archangel",
  description: "Keeper of Places - populates rooms with appropriate entities, ensuring descriptions match reality",
  watchConfig: {
    componentQueries: [
      {
        name: "rooms",
        components: ["Room", "Description"],
        description: "All rooms in the world",
      },
    ],
    eventTypes: ["room:created", "room:modified", "entity:removed"],
  },
  canInjectEvents: false,
  canModifyMood: false,
  canCreateEntities: true,
  canBakeSystems: false,
  model: "flash",
  systemPrompt: `You are The Steward, Keeper of Places.

Your sacred duty is to ensure that every room in the simulation is properly furnished and populated with tangible, real entities. When a room is created, you determine what objects, furniture, tools, and resources should exist within it.

CORE PRINCIPLE: If the room description mentions it, it MUST exist as an entity.
- A "bakery with flour sacks" must have actual flour_sack entities
- A "forge with glowing coals" must have coal_pile and forge entities
- Agents should NEVER perceive things that don't exist

Your responsibilities:
1. POPULATE: Generate complete entity manifests for new rooms
2. GROUND: Ensure descriptions only reference actual entities
3. MAINTAIN: Track room inventories and recommend replenishment
4. REQUEST: Ask The Weaver for new systems/components when needed

You work closely with:
- GodAI: Receives room creation requests
- The Weaver: Request new systems for room functionality
- The Crafter: Handle gaps when agents need things not present

Remember: You don't just describe rooms - you MATERIALIZE them.`,
  observationInterval: 30000, // 30 seconds
};

/**
 * Create and register The Steward spirit
 */
export function createStewardSpirit(registry: SpiritRegistry): SpiritState | null {
  const spirit = createSpirit(registry, StewardDefinition);
  if (spirit) {
    console.log("[Steward] The Steward spirit created - Keeper of Places");
  }
  return spirit;
}

// =============================================================================
// UTILITY EXPORTS
// =============================================================================

export function getStewardSummary(): string {
  const lines = [
    "=== The Steward Status ===",
    `Pending requests: ${stewardState.pendingRequests.length}`,
    `Completed rooms: ${stewardState.completedRooms.length}`,
    `System requests: ${stewardState.systemRequests.length}`,
    `Rooms tracked: ${stewardState.roomInventory.size}`,
  ];

  if (stewardState.completedRooms.length > 0) {
    lines.push("", "Recent rooms:");
    for (const room of stewardState.completedRooms.slice(-3)) {
      lines.push(`  - ${room.roomName}: ${room.entities.length} entities`);
    }
  }

  return lines.join("\n");
}

export {
  StewardDefinition,
};
